apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-nginx
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: main-app-nginx
  template:
    metadata:
      labels:
        app: main-app-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
        - name: media-volume
          mountPath: /app/media
      dependsOn:
      - main-app
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
