apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: your_repo_name/frontend:latest # Replace with your actual image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-volume
          mountPath: /app
      volumes:
      - name: frontend-volume
        persistentVolumeClaim:
          claimName: frontend-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
