apiVersion: v1
kind: Service
metadata:
  name: main-app-service
spec:
  selector:
    app: main-app
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8001
    nodePort: 30001 # You can choose a different NodePort
